server:
  port: 8080
  servlet:
    context-path: /bifrost-beacon
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    create:
      jdbc-url: ${SPRING_DATASOURCE_CREATE_JDBC_URL:jdbc:postgresql://127.0.0.1:5632/riglightwatch-db}
      username: ${SPRING_DATASOURCE_CREATE_USERNAME:bifrost_beacon}
      password: ${SPRING_DATASOURCE_CREATE_PASSWORD:postgres}
    write:
      jdbc-url: ${SPRING_DATASOURCE_WRITE_JDBC_URL:jdbc:postgresql://127.0.0.1:5632/riglightwatch-db}
      username: ${SPRING_DATASOURCE_WRITE_USERNAME:bifrost_beacon}
      password: ${SPRING_DATASOURCE_WRITE_PASSWORD:postgres}
      max-connections: ${SPRING_DATASOURCE_WRITE_MAX_CONNECTIONS:2}
    read:
      jdbc-url: ${SPRING_DATASOURCE_READ_JDBC_URL:jdbc:postgresql://127.0.0.1:5632/riglightwatch-db}
      username: ${SPRING_DATASOURCE_READ_USERNAME:bifrost_beacon}
      password: ${SPRING_DATASOURCE_READ_PASSWORD:postgres}
      max-connections: ${SPRING_DATASOURCE_READ_MAX_CONNECTIONS:2}
  jpa:
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_HIBERNATE_FORMAT_SQL:true}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
logging:
  gelf:
    host: ${LOGGING_GELF_HOST:127.0.0.1}
    port: ${LOGGING_GELF_PORT:12201}