server:
  port: 8080
  servlet:
    context-path: /bifrost-beacon
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    create:
      url: ${SPRING_DATASOURCE_CREATE_URL:jdbc:postgresql://127.0.0.1:5432/riglight-watch-db}
      jdbc-url: ${SPRING_DATASOURCE_CREATE_JDBC_URL:jdbc:postgresql://127.0.0.1:5432/riglight-watch-db}
      username: ${SPRING_DATASOURCE_CREATE_USERNAME:bifrostbeacon}
      password: ${SPRING_DATASOURCE_CREATE_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_HIBERNATE_FORMAT_SQL:true}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
logging:
  gelf:
    host: ${LOGGING_GELF_HOST:127.0.0.1}
    port: ${LOGGING_GELF_PORT:12201}